### ISSUE TITLE
partition_by_locus.R error

### ISSUE THREAD

**Issue by ymilesz** [laninsky/UCE_processing_steps#2]
Hi Alana,

  I am trying to run your script for the partition_by_locus.R in order to do SWSC, but I get the following error:

Error in finalnameseq[, 1] <- unlist(strsplit(firstrows, "\\s"))[seq(1,  : 
  number of items to replace is not a multiple of replacement length

**Comment by laninsky** [comment]
Heyo Miles,This script should be run in your phylip_w_missing folder (e.g. every taxon should be present for every UCE). Once inside that folder:

Rscript partition_by_locus.R
This will output a file outputdata.nex

Note: you can also achieve this with phyluce using the format_nexus_files_for_raxml script and the --nexus and --charsets flags (thanks to Dr. Michael Branstetter for pointing this out).

**Comment by laninsky** [comment]
Heyo Miles,

Could I get you to shoot me say, five of your phylip files or so? That'll probably be the quickest way for me to work out why my code is buggy! Also, just an FYI, you can achieve the same outcome with phyluce using the format_nexus_files_for_raxml script and the --nexus and --charsets flags, in case you'd rather that option.

Cheers,

Alana

**Comment by laninsky** [comment]
It wasn't obvious from the README for this script, but it needs to be run on the phyluce output folder that has a separate phylip file per locus, but where you have each taxon present (i.e. missing data has been "added" based on the phyluce pipeline). The code we used for this is here: https://github.com/laninsky/UCE_processing_steps#adding-missing-data-designators , but names have to be lower case and the adding-missing-data-designators script has to be run with --verbatim for it to work due to this issue: https://github.com/faircloth-lab/phyluce/issues/34 . Updating the README to make all of this a little clearer for the next person who tries to use it! Thanks for flagging this @ymilesz !
